name: Robot Framework API Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
    Run-Test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v1
        - name: Install pip dependencies
          run: |
             python -m pip install --upgrade pip
             pip install robotframework
             pip install robotframework-requests
        - name: Run Test
          run: robot .
       
